### ISSUE TITLE
Missing value sentinel

### ISSUE THREAD

**Issue by MicaelJarniac** [python-attrs/cattrs#178]
Essentially, my suggestion is to add a simple way to register a structure hook for `Union[x, y]`, where `x` is a sentinel type that represents a missing attribute, and `y` is a valid type.

It'd work basically the same way as `Optional[y]`, but instead of only working with `Union[None, y]`, it'd work for an arbitrary sentinel `x`.

This sentinel in question would represent that the given attribute was not found when structuring, and therefore, if any value is found, it'd be safe to completely ignore type `x` and treat it as just type `y`.

And the other way around too: when unstructuring, if an attribute is that sentinel, it won't be included.

This would allow the use of `None` as a valid value for certain attributes.

---

`sentinels.py`:
```py
from enum import Enum
from typing import TypeVar, Union


class Missing(Enum):
    MISSING = None


MISSING = Missing.MISSING  # This is the value that's used as the sentinel. It is of type `Missing`.
T = TypeVar("T")
OptMissing = Union[T, Missing]  # This is basically a macro for easy type-hinting, similar to `Optional[...]`
```

This is just one possible implementation of a sentinel. I've chosen this one basically because it's easy to type-hint, but ideally, any implementation that can be type-hinted should work.

---

`test.py`:
```py
import attr
import cattr

from sentinels import OptMissing, MISSING, Missing

cattr.register_missing(Missing)  # This would tell cattr that `Missing` is a sentinel type, just like `None`


@attr.s
class Foo:
    bar: OptMissing[int | None] = MISSING


cattr.structure({}, Foo)  # If no value is found for the `OptMissing` attribute, it'll use the default value
# Foo(bar=<Missing.MISSING: None>)

cattr.structure({"bar": 1}, Foo)  # If a value is found, it'll use the type other than `Missing` for the conversion
# Foo(bar=1)

cattr.structure({"bar": "2"}, Foo)  # So this is basically as if the type hint for `bar` was only `int | None`
# Foo(bar=2)

cattr.structure({"bar": None}, Foo)
# Foo(bar=None)

a = Foo()  # If nothing is provided for `bar`, it's of type `Missing`, and not included when unstructuring
cattr.unstructure(a)
# {}

b = Foo(bar=1)
cattr.unstructure(b)
# {"bar": 1}

c = Foo(bar=None)
cattr.unstructure(c)
# {"bar": None}
```

---

**Comment by Tinche** [comment]
Hello!

This is an interesting idea. I think it's a little too opinionated to include in cattrs proper though. The good news is that cattrs can already do this, and without too much fuss. Here's what you need to do. I'll be using Python 3.10 and cattrs `main`, and omitting imports for brevity.

First, your preamble, setting up the problem:

```python
class Missing(Enum):
    MISSING = None


MISSING = Missing.MISSING
T = TypeVar("T")
OptMissing = T | Missing


@define
class Foo:
    bar: OptMissing[int | None] = MISSING
```

Since we'll be customizing cattrs behavior, we need an instance of the `GenConverter` just for ourselves. We're using `MISSING` for the default value, so we can get the unstructuring behavior we want by passing `omit_if_default` to the GenConverter.

```python
c = GenConverter(omit_if_default=True)
```
If we try unstructuring now, the converter will complain it can't handle `OptMissing`. Since we're using `omit_if_default`, we don't really need to go any special unstructuring work, the converter will filter it out for us. We just need to tell the converter to unstructure it anyway, using the runtime type (so, using the rules for `int`, `None` or `Enum`, instead of `OptMissing`.

```python
# A helper predicate function, so we can recognize unions that contain `Missing`.
from cattr._compat import is_union_type, get_args
has_missing = lambda t: is_union_type(t) and Missing in get_args(t)

c.register_unstructure_hook_func(has_missing, lambda o: c.unstructure(o))
```

Now this works:

```python
assert c.unstructure(Foo()) == {}
assert c.unstructure(Foo(1)) == {"bar": 1}
assert c.unstructure(Foo(None)) == {"bar": None}
```

On to structuring, which is a little more involved. Since `MISSING` is the default value for `Foo.bar`, it'll get set by default if the key is missing in the input data. We just need to teach cattrs how to handle the scenario when the key is present.

We're going to do a little Python type system black magic. If we structure a union type containing `Missing`, we're going to structure it as a union type with all the other arguments, but without `Missing`. So we treat `int | None | Missing` as `int | None` instead. Here's how:

```python
c.register_structure_hook_func(
    has_missing,
    lambda v, t: c.structure(
        v, Union[tuple(a for a in get_args(t) if a is not Missing)]
    ),
)
```

So now this works:

```python
assert c.structure({}, Foo) == Foo()
assert c.structure({"bar": 1}, Foo) == Foo(1)
assert c.structure({"bar": "2"}, Foo) == Foo(2)
```
Hope this helps!

**Comment by MicaelJarniac** [comment]
Thanks a lot! I just tested it here and it seems to work perfectly!

I did try implementing it manually before opening the issue, but I was puzzled by a few things and didn't know exactly how to approach this. I even poked inside the source to see how `Optional` worked, but still couldn't figure out what to do.

One thing that I'm having a bit of trouble with is the type of the arguments for `is_union_type` and `get_args`.

The following works, but `mypy` complains about a couple of things:

```py
def configure_converter_missing(converter: cattr.Converter) -> None:
    c = converter

    def has_missing(t) -> bool:
        return is_union_type(t) and Missing in get_args(t)

    c.register_unstructure_hook_func(has_missing, lambda o: c.unstructure(o))
    # c: Cannot infer type argument 1 of "register_unstructure_hook_func" of "Converter" - mypy(error)

    c.register_structure_hook_func(
        has_missing,
        lambda v, t: c.structure(
        # c: Return statement in function which does not return - mypy(error)
            v, Union[tuple(a for a in get_args(t) if a is not Missing)]
            # Union[...]: Argument 2 to "structure" of "Converter" has incompatible type "object"; expected "Type[<nothing>]" - mypy(error)
            # Union[...]: Union requires two or more type arguments - Pylance
        ),
    )
```

From what I can tell, the type of `t` should be `_GenericAlias` from `typing`, but I can't manage to import it.

**Comment by MicaelJarniac** [comment]
For now, I've thrown some `# type: ignore` comments at it and `mypy` stops complaining, but it'd be pretty nice to have it correctly typed.

**Comment by Tinche** [comment]
Unfortunately code like this is too high level/meta to be properly type checked at this time, and it'll probably be a while. (For an example, see https://github.com/python/mypy/issues/9773.)

**Comment by MicaelJarniac** [comment]
That's unfortunate (and kind of ironic IMO, that the system behind type hints can't be type hinted itself).

Thanks again for everything :D I'll close this issue now.
