### ISSUE TITLE
[Question]: Why use `cattr.preconf`?

### ISSUE THREAD

**Issue by blthayer** [python-attrs/cattrs#222]
Hello, and thanks for `cattrs`!

I'm trying to understand the use case for `cattr.preconf`, _specifically_ for `cattr.preconf.orjson`.

Looking at the [docs](https://cattrs.readthedocs.io/en/latest/preconf.html) and the [source](https://github.com/python-attrs/cattrs/blob/main/src/cattr/preconf/orjson.py), using `cattr.preconf.orjson.configure_converter` (or `make_converter`) simply registers some hooks for `bytes` and `datetime`.

Why not just leave the work of handling `bytes` and `datetime` to `orjson` which is already hyper-optimized for speed?

The workflow I generally use with `cattrs` + `orjson` is like so:

**Deserialize**
`input_data` -> `orjson.loads` -> `converter.structure`

Where `input_data` is `bytes` coming in from the outside (e.g. over the network), and `converter` is a `GenConverter` instance.

**Serialize**
`my_data` -> `converter.unstructure` -> `orjson.dumps`

Where `my_data` is an arbitrary Python object in my program, and `converter` is a `GenConverter` instance.

In the workflow I've illustrated above, during serialization `cattrs` will convert any `datetime` instances in `my_data` to a string (assuming we've configured our converter via `cattr.preconf.orjson.configure_converter`), so `orjson` never even sees any `datetime` instances.

This makes me ask the question: Why would I even use `cattr.preconf.orjson`?

Thank you for your time!

**Comment by Tinche** [comment]
It's essentially because I didn't get around to it. If orjson handles datetimes the same as we would, I'd have no problem configuring the converter to just pass the datetimes through.

**Comment by blthayer** [comment]
Thanks for your quick response!

I'm not sure if you envision `cattrs` using some sort of unified `datetime` handling behavior, but `orjson` serializes `datetime` to RFC3339 ([source](https://github.com/ijl/orjson#datetime)).

For my use case, I'll simply skip using `cattr.preconf` for now. Thanks again!

**Comment by Tinche** [comment]
It looks like RFC3339 is a subset of ISO8601, so that might be compatible. I might consider just passing datetimes through for orjson.

cattrs is supposed to be the layer between your structured data and the serialization library, so if you wanted your datetimes to be serialized as unix timestamps, `orjson` obviously cannot do that and you'd have to use cattrs for that. That said, one of the objectives of cattrs is to be as fast as possible, and that means doing as little work as possible. So if orjson can do the date conversion faster than us and still keep the result acceptable, we should let it.
