### ISSUE TITLE
cattrs.__all__ contains unimported "GenConverter"

### ISSUE THREAD

**Issue by sscherfke** [python-attrs/cattrs#289]
The `__all__` list in `cattrs/__init__.py` [contains GenConverter](https://github.com/python-attrs/cattrs/blob/main/src/cattrs/__init__.py#L22) but it is not imported.

**Comment by sscherfke** [comment]
But `cattrs.GenConverter` will keep working in 22.2, won't it?  You will not introduced a breaking change, won't you? 😇

**Comment by aarnphm** [comment]
For 22.2 GenConverter now is an alias to Converter. The current Converter is renamed to BaseConverter.

**Comment by sscherfke** [comment]
Yes, I’ve read this.  I just wanted @Tinche to confirm that the mistake was not "not removing GenConverter from __all__" but "not setting `GenConverter = Converter` in `cattrs.__init__`" :)

**Comment by aarnphm** [comment]
Seems like cattrs is relying on import side effect here. Since GenConverter is defined under [`.converter.py`.(https://github.com/python-attrs/cattrs/blob/56eda3719e4203792c0557f8539dca24e15258d4/src/cattrs/converters.py#L840), this means when we have relative imports GenConverter should already be included in `locals()` of `cattrs/__init__.py`.

(printed from locals() of `cattrs/__init__.py`.
![Uploading Screenshot 2022-07-08 at 14.42.08.png…]()

**Comment by Tinche** [comment]
I'm confirming the `GenConverter` name should still be available. No need to cause even more breakage for no reason ;)

**Comment by Tinche** [comment]
Fixed on `main`!
