### ISSUE TITLE
Converting "FALSE" to boolean

### ISSUE THREAD

**Issue by klausmcm** [python-attrs/cattrs#294]
* cattrs version: 22.1.0
* Python version: 3.7.3
* Operating System: Debian 10

### Description

``` python
from attrs import define
import cattrs

@define
class MyClass:
    flag: bool
    name: str

d = {"flag": "FALSE", "name": "abc"}

c = cattrs.structure(d, MyClass)
print(c)
```

The output I get

`MyClass(flag=True, name='abc')`

but this is what I would like to get

`MyClass(flag=False, name='abc')`

### What I Did

See above

---

I know I can preprocess the dictionary before calling `cattrs.structure` but is there a way that I can map `FALSE` (str) to `False` (bool) using cattrs? I have been reviewing the documentation on converters but I'm not sure yet if I'm looking in the right place.

Thanks,

**Comment by klausmcm** [comment]
I tried the following

``` python
from attrs import define, field
import cattrs


def conv_bool(string):
    return {"FALSE": False, "TRUE": True}.get(string)


@define
class MyClass:
    flag: bool = field(converter=conv_bool)
    name: str


d = {"flag": "FALSE", "name": "abc"}

c = cattrs.structure(d, MyClass)
print(c)
```

but that gives me `MyClass(flag=None, name='abc')`. By the time `conv_bool` is called, the `string` is already a boolean (`True`) so the function returns `None` because `True` is not in the lookup dictionary.

**Comment by Tinche** [comment]
So the simplest solution is to register a converter hook for `bool`. The default one just calls `bool()` on the argument, and `bool("FALSE") is True` in Python by default.

Since you'll be changing state (by registering the hook) a good pattern is to get your own converter instead of using the global one.

Here's the code:

```python
from attrs import define

from cattrs import GenConverter  # will be just Converter in the next version

converter = GenConverter()
converter.register_structure_hook(
    bool, lambda v, _: {"FALSE": False, "TRUE": True}.get(v)
)


@define
class MyClass:
    flag: bool
    name: str


d = {"flag": "FALSE", "name": "abc"}

c = converter.structure(d, MyClass)
print(c)
```
You can get fancier if you want, let me know.

**Comment by klausmcm** [comment]
Perfect. Thank you!

**Comment by whardier** [comment]
I would like to see fancier please.

I found this issue and have "solved" it this way:

```python
@define
class TracingConfig:
    sampling: float = field(default=1, converter=converters.optional(float))
    enabled: bool = field(default=True, converter=converters.to_bool)

@define
class PlatformConfig:
    tracing: TracingConfig = field(factory=partial(TracingConfig))
    
@define
class Config:
    platform: PlatformConfig = field(factory=partial(PlatformConfig))
    
converter.register_structure_hook(bool, lambda v, _: converters.to_bool)
converter.structure(obj, Config)
```

As well as this way:

```python
@define
class TracingConfig:
    sampling: float = field(default=1, converter=converters.optional(float))
    enabled: Union[bool,str] = field(default=True, converter=converters.to_bool)

@define
class PlatformConfig:
    tracing: TracingConfig = field(factory=partial(TracingConfig))
    
@define
class Config:
    platform: PlatformConfig = field(factory=partial(PlatformConfig))
    
converter.structure(obj, Config)
```

And I very much dislike the latter.. but it's less invasive than the former (all bools must conform!)

**Comment by Tinche** [comment]
I agree your first snippet looks better. 

A small tip: you don't need to do `partial(TracingConfig)` in your defaults, you can just do `factory=TracingConfig` (or import `Factory` from attrs and just do `tracing: TracingConfig = Factory(TracingConfig)`.

I see you're using attrs converters in the snippet - know that cattrs will use its own rules first, by default. So you'll likely be running them twice - once by cattrs, and once by the class (attrs). Probably not a big deal unless this is a hot path. If you're always loading in the data via cattrs you can remove the converters and just override the `bool` structure function in cattrs, like you're already doing.

This line:
```python
converter.register_structure_hook(bool, lambda v, _: converters.to_bool)
```
looks a little fishy, I think it should be:
```python
converter.register_structure_hook(bool, lambda v, _: converters.to_bool(v))
```
Anything in particular you'd like help with?

**Comment by whardier** [comment]
Thanks for the tip.  I found the `Factory` bit a bit earlier today while scanning through GitHub because it just seemed so wrong.  FWIW `field(factory=OtherAttrClass)` makes `mypy` very upset.

You are right that I missed passing a variable.  I was using a custom function (no lambda) that accepted all the args so that I could see what was happening and "fixed it" to show converters.to_bool via a lambda for my example and forgot to make it complete.

From what I can tell - cattrs is looking at annotations and then if the annotation doesn't line up it just uses the default for the field.  I'm wondering if there is a way to loosen this up a bit so that if the annotation doesn't match then the field converter is applied.  I think that's somewhat implied but caught me as well as the OP for this ticket.

**Comment by Tinche** [comment]
Close but not quite. The presence of a default only determines whether cattrs does an `input.get()` or a `input[]` operation on the incoming data.

Also note that cattrs does coercion by default, not checking. So if a field is annotated as a `bool`, cattrs will look up the hook in charge of handling bool and run it with the input value, and the bool hook will just run the `builtins.bool` function on the value and return that. The same goes for most of the other primitives, like ints, strings and so on.
