### ISSUE TITLE
GenConverter doesn't use registered unstructure hooks when unstructuring attrs classes

### ISSUE THREAD

**Issue by larchen** [python-attrs/cattrs#329]
* cattrs version: 22.2.0
* Python version: 3.10.8
* Operating System: Windows 10

### Description

I'd like to be able to unstructure all sets as lists but it seems that GenConverter is not using the registered unstructure hooks as I expected. Is this the defined behavior? If so how would you recommend getting the desired behavior?

```
from attrs import define, frozen
from cattr import GenConverter

@frozen
class B:
    b: str = ''

@define
class A:
    a: set[B]

converter = GenConverter()
obj = A(
    a={B()}
)

converter.register_unstructure_hook(
    set,
    lambda obj: list(converter.unstructure(el) for el in obj)
)

converter.unstructure(obj)
```
This throws an error because `B` gets unstructured as a `dict` which is now unhashable. What I would like is to have this unstructured as `{'a': [{b: ''}]}`.

**Comment by Tinche** [comment]
Hello!

So the reason it doesn't work is because cattrs uses `functools.singledispatch` under the hood when you use `register_unstructure_hook`, and `set[B]` is not a subclass of `set`. So you could solve it by using a predicate hook instead.

But since this is a common thing, the converter supports these overrides out-of-the-box. Try this:

(`GenConverter` is equivalent to `Converter` in the latest versions)

```python
from attrs import define, frozen

from cattrs import Converter


@frozen
class B:
    b: str = ""


@define
class A:
    a: set[B]


converter = Converter(unstruct_collection_overrides={set: list})

obj = A(a={B()})


converter.unstructure(obj)

```

You can read more about this feature [in the docs](https://catt.rs/en/stable/unstructuring.html#customizing-collection-unstructuring).

**Comment by larchen** [comment]
Thanks! I missed this when looking at the docs but this is exactly what I was looking for.
