### ISSUE TITLE
Allow registering structuring hooks for specific input types

### ISSUE THREAD

**Issue by moloney** [python-attrs/cattrs#331]
* cattrs version: latest
* Python version: 3.10
* Operating System: Linux

### Description

I am trying to use cattrs for the deserialization part of a configuration system. Some objects can be "inline" configurable, meaning they can parse a single string into the attributes they need (in addition to being able to be configured through a dict the "normal" way). For example maybe a class with "host" and "port" attributes can parse the string "example.com:443". 

My first thought was to create a base class / protocol with an abstract method for parsing the string into a dictionary, then register a structure hook for all subclasses that would call this method. Unfortunately there is now no clear escape hatch that allows me to call the regular structuring code on this class (using dict input, or the dict result from parsing the string).

Ideally I would register this hook so that is only called for subclasses if the input value is a string.

### What I Did

```python
class InlineConfigurable(Protocol):
    @classmethod
    def inline_to_dict(cls, in_str: str) -> Dict[str, Any]:
        raise NotImplementedError

conv = cattrs.Converter()
# THIS WILL CAUSE INFINITE RECURSION
conv.register_structure_hook(
    InlineConfigurable, lambda v, t: conv.structure(t.inline_to_dict(v), t) if isinstance(v, str) else conv.structure(v, t)
)
# WOULD BE NICE TO BE ABLE TO DO SOMETHING LIKE
#conv.register_structure_hook_w_input(
#    (InlineConfigurable, str), lambda v, t: conv.structure(t.inline_to_dict(v), t)
#)

@dataclass
class RemoteNode(InlineConfigurable):
    host: str
    port: int

    @classmethod
    def inline_to_dict(cls, in_str: str) -> Dict[str, Any]:
        toks = in_str.split(":")
        return {"host": toks[0], "port": toks[1]}
```

**Comment by Tinche** [comment]
Howdy!

This is a cool use case.

So there are two ways to do this currently, one is simpler but slower, the other faster but a little more complex. If you're just parsing some configuration once, the slower way is just fine.

The simpler one just delegates to `converter.structure_attrs_fromdict`, which is kind of a legacy thing. This function is how cattrs used to work before we had the generator stuff.

Here's the simpler version:
```python
from dataclasses import dataclass
from typing import Any, Protocol

import cattrs


class InlineConfigurable(Protocol):
    @classmethod
    def inline_to_dict(cls, in_str: str) -> dict[str, Any]:
        raise NotImplementedError


conv = cattrs.Converter()

conv.register_structure_hook(
    InlineConfigurable,
    lambda v, t: conv.structure_attrs_fromdict(t.inline_to_dict(v) if isinstance(v, str) else v, t)
)

@dataclass
class RemoteNode(InlineConfigurable):
    host: str
    port: int

    @classmethod
    def inline_to_dict(cls, in_str: str) -> dict[str, Any]:
        toks = in_str.split(":")
        return {"host": toks[0], "port": toks[1]}


print(conv.structure("host:443", RemoteNode))
print(conv.structure({"host": "host", "port": 443}, RemoteNode))
```

Note: even though I say this is a legacy way, it's not getting removed, partly due to backwards compatibility and partly because it's still sometimes useful.

Now, the second way involves hook factories. Hook factories are like hooks, except one layer removed - so instead of registering a hook, you register something that produces hooks.

This is the idea: you actually need two ways of structuring an `InlineConfigurable`. The first way is the default way, where fields in a dict are mapped to fields in a class. The other way involves a pre-processing step, and then it's basically a wrapper around the first way. The reason you need a hook factory instead of a hook is that the first way is different for every different `InlineConfigurable`.

Here's the solution:

```python
from cattrs.gen import make_dict_structure_fn

def _make_structure_hook(type):
    original_hook = make_dict_structure_fn(type, conv)

    def wrapper_hook(val, _):
        if isinstance(val, str):
            val = type.inline_to_dict(val)
        return original_hook(val, _)

    return wrapper_hook

conv.register_structure_hook_factory(lambda t: issubclass(t, InlineConfigurable), _make_structure_hook)
```
So it's a little more complex but super powerful.

For this reason I'm not inclined to add any additional functionality to cattrs at this time, I feel the use case here is already served relatively well, and it would just increase the API surface.

Let me know if this works for you!

**Comment by moloney** [comment]
Thanks for the quick response! Both of your solutions do indeed work for me. While initially I thought they might not work in the recursive (nested) case I did some testing and found that they do. So for example I can do:

```python
@dataclass
class Route(InlineConfigurable):
    src: RemoteNode
    dest: RemoteNode

    @classmethod
    def inline_to_dict(cls, in_str: str) -> Dict[str, Any]:
        toks = in_str.split("/")
        return {"src": toks[0], "dest": toks[1]}

print(conv.structure("host1:443/host2:443", Route))
print(conv.structure({"src": "host1:443", "dest": "host2:443"}, Route))
print(
    conv.structure(
        {"src": {"host": "host1", "port": 443}, "dest": {"host": "host2", "port": 443}},
        Route,
    )
)
```

The hook factories do indeed look quite powerful and I will need to spend some time looking into them. Thanks for your time!
