### ISSUE TITLE
Error when registering a Literal

### ISSUE THREAD

**Issue by joshmalina** [python-attrs/cattrs#332]
* cattrs version: 22.2.0
* Python version: 3.11
* Operating System: OSX

### Description

I'm trying to register a Literal, but can't once I upgraded to python 3.11.

### What I Did
<img width="1016" alt="Screen Shot 2023-02-07 at 11 00 15 AM" src="https://user-images.githubusercontent.com/5384924/217296760-3ec4f56e-5d27-4b94-baf8-f083905e0791.png">

**Comment by Tinche** [comment]
It doesn't seem to work on 3.10 either. From which version are you upgrading?

**Comment by Tinche** [comment]
Guess `functools.singledispatch` (which is what gets used for `register_structure_hook`) doesn't work with literals any more. You can try opening a bug against CPython, but there's a good chance you won't get very far unfortunately. I'm wary of adding support for things like this since there are a ton of edge cases and it adds maintenance burden.

_cattrs_ already has a simple escape hatch you can use when singledispatch isn't appropriate. You can use `register_structure_hook_func` instead, and give it a predicate (a function that takes a type and returns True/False if it can handle it). Here it is:

```python
from typing import Literal

from cattrs import Converter

dogs = Literal['ace', 'mac', 'spot']

c = Converter()
c.register_structure_hook_func(lambda t: t is dogs, lambda v, _: v.upper())

print(c.structure("ace", dogs))
```

**Comment by joshmalina** [comment]
Wonderful, thank you @Tinche
