### ISSUE TITLE
Explicitly specify the field which does not require structuring

### ISSUE THREAD

**Issue by dmfigol** [python-attrs/cattrs#50]
* cattrs version: 0.9.0
* Python version: 3.6.6
* Operating System: macOS

### Description

I use cattrs + attrs (w/ type annotations and `auto_attribs=True`) + marshmallow. Marshmallow does data normalization and then the data is passed through cattr converter to be deserealized into Python objects. When the data is normalized, I already get proper "simple" types, like datetime, so I don't need another conversion.
I would like to indicate to cattrs that it should not do conversion, ideally on per field basis, not on per type basis.
Currently, I specify `lambda x, _: x` converter per type. 

I have similar problem when I specify Union of different types. Those can be float, str, datetime and I don't need to convert them.
May be it is already possible, but I haven't found this in the docs.

`typing.Any` is not desirable, because then I lose my types

**Comment by Tinche** [comment]
Howdy. I'm finally doing some housekeeping and going over older issues, so apologies for the uh, 4.5 year delay ;)

Since this request is for per-field overrides, this is possible since the last version using the [new `override(struct_hook)` parameter](https://catt.rs/en/stable/customizing.html#struct-hook-and-unstruct-hook). Here's an example in which the struct hook is overridden using an identity lambda:

```python
from datetime import datetime

from attrs import define

from cattrs import Converter, override
from cattrs.gen import make_dict_structure_fn


@define
class A:
    dt: datetime


c = Converter()
c.register_structure_hook(
    A, make_dict_structure_fn(A, c, dt=override(struct_hook=lambda x, _: x))
)

print(c.structure({"dt": datetime.now()}, A))

```
