### ISSUE TITLE
Unsupported type: typing.Union[int, typing.List[int], str]. Register a structure hook for it.

### ISSUE THREAD

**Issue by wencan** [python-attrs/cattrs#559]
cattrs            23.2.3
Python 3.11.2
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-23-amd64 

I can implement a structure hook to solve this problem. But I want to know if there's a simpler solution. I've learned that cattrs has already implemented a configure_tagged_union function. After reading the documentation, I tried to use configure_tagged_union to solve my problem, but all attempts failed.

```python
from dataclasses import dataclass
from typing import List, Union
from cattrs import structure


@dataclass
class Request:
    code: str
    options: List[Union[int, List[int], str]]


data = {
    "code": "test",
    "options": [1, [2, 3], "5"]
}

r = structure(data, Request)
print(r)
```

error:
```
      | cattrs.errors.StructureHandlerNotFoundError: Unsupported type: typing.Union[int, typing.List[int], str]. Register a structure hook for it.
      | Structuring typing.List[typing.Union[int, typing.List[int], str]] @ index 1
```

**Comment by salotz** [comment]
A union strategy wouldn't help in this scenario. Its only necessary for class-like structs that might have the same keys.

I'm not sure what the issue is though. This should be enough information for a generic handler to deal with.

**Comment by Tinche** [comment]
The short answer: you're going to have to write your own handler for this union, use a preconf converter or apply the `union_passthrough` strategy to a converter. No, the tagged union strategy won't help since it needs the union to be of dataclasses or attrs classes, and it would expect the payload to be like `"options": [{"_type": int, "value": 1}]` which is not the case here.

Now, the long answer is somewhat complex.

cattrs by default uses coercion instead of validation. This means when handling an `int`, cattrs will do `int(input)` instead of `if not isinstance(input, int): raise Exception`. This can help compatibility (it's common to stringify large integers in Javascript, for example) and performance (it's significantly faster). This also means we can't easily solve a type like `str | int`.

Even if we changed this logic slightly, I think the flow @salotz was envisioning was:

```python
if isinstance(input, int):
    return input
elif isinstance(input, str):
   return input
elif isinstance(input, list):
    return input
else:
    raise Exception()
```

I think this is, in broad strokes, how some other serialization libraries handle unions.

I've been very careful to never do this in cattrs for several reasons. First, it can make the ordering of union members significant, but in the type system `str | int` should be equivalent to `int | str`. Second, the deserialization time will be O(length of union), which is pretty bad.

Now, **there is a trick**. If your data is coming from a well-known serialization library, like the standard library `json` module or `orjson`, this changes things a little, because these libraries will generally never produce a subclass of `str` or `int`. This means instead of the chain of `ifs`, we can just do a set check:

```
if type(input) in {int, str}:
    return input
return structure(input, list[int])
```

This is accomplished by the [union passthrough strategy](https://catt.rs/en/stable/strategies.html#union-passthrough), and this strategy is automatically applied to all preconf converters. (You can also apply this strategy to any converter if you want.)

So if your data is coming from the `json` module, this will work:

```python
from dataclasses import dataclass
from typing import List, Union

from cattrs.preconf.json import make_converter


@dataclass
class Request:
    code: str
    options: List[Union[int, List[int], str]]


data = {"code": "test", "options": [1, [2, 3], "5"]}

c = make_converter()

r = c.structure(data, Request)
print(r)
```

Hope this helps!
