### ISSUE TITLE
Is there a way to recursively prefer `_cattrs_use_alias=True`?

### ISSUE THREAD

**Issue by BrianPugh** [python-attrs/cattrs#596]
In my application, i have several nested structures that have attrs aliases set (e.g. `field(..., alias="foo")`). I am aware that I could individually register a hook for every class with:
```python
converter.register_structure_hook(
    MyClass,
    make_dict_structure_fn(MyClass, converter, _cattrs_use_alias=True),
)
```

However, this requires the developer to remember to do that for every new class. Is there a way of applying this setting for the whole converter?

**Comment by BrianPugh** [comment]
I *think* the solution is:
```
import attrs
import cattrs

converter.register_structure_hook_factory(
    attrs.has,
    lambda cl: cattrs.gen.make_dict_structure_fn(cl, converter, _cattrs_use_alias=True)
)
```

would love to have @Tinche to chime in if this is the intended solution! Thanks!

**Comment by Tinche** [comment]
You got to it before I did! That's exactly what I would have suggested.

**Comment by BrianPugh** [comment]
thank you!

**Comment by AdrianSosic** [comment]
Hi @Tinche, I just stumbled over this issue because I was looking for the same functionality. While the proposed solution works, is comes with the downside that you need to remember setting the flag whenever you register a regular singledispatch hook for a class using `make_dict_structure_fn`, because that takes preference over the hook factory. And if you forget, this might break your exposed APIs that rely on these converters.

Therefore a question: wouldn't it perhaps make sense to add a `use_alias` argument to `Converter` that is then extracted a la `from_converter` in `make_dict_(un)structure_fn_from_attrs`, just like other settings such as `forbid_extra_keys`? The nice consequence would be that this would then work together with added hooks, if I'm not mistaken?

**Comment by Tinche** [comment]
Hm, if you want to contribute it, sure, why not.
