### ISSUE TITLE
Specific container type isn't respected, e.g. list can populate set

### ISSUE THREAD

**Issue by vreuter** [python-attrs/cattrs#602]
* cattrs version: 24.1.2
* Python version: 
```console
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=11, micro=9, releaselevel='final', serial=0)
```
* Operating System: macOS Ventura

### Description

Structure raw data into an instance of a class, in such a way that _container_ type is respected.

### What I Did

```python
>>> @define
... class C:
...     a: int
...     b: set[str]
...
>>> instance = structure({'a': 1, 'b': ['x', 'y']}, C)
>>> instance
C(a=1, b={'x', 'y'})
```

### What I Expect

I expect a failure, since the `list[str]` value for the `b` key doesn't conform to the `set[str]` type of the corresponding member of the class. This violates separation of concerns: the `structure` call is also deduplicating elements of the list, then, for the conversion to a set. As such, a reasonable invariant like "each collections in the raw data should have the same size as the corresponding collection once structured into the class" can be violated.

**Comment by vreuter** [comment]
Possibly related to #44 ?

**Comment by Tinche** [comment]
Yeah, the hooks for various collections only require [the input type is iterable](https://catt.rs/en/stable/defaulthooks.html#sets-and-frozensets). Validating the exact input types would be less useful - you wouldn't be able to use `set[T]` in anything loaded from json since no json library produces sets.

I think it helps to think of cattrs as a tool for transformations, not direct validations - dicts get turned into classes, strings into enums, iterables into collections.

The use case you describe is possible. You can opt into stricter validation for lists as [documented here](https://catt.rs/en/stable/customizing.html#customizing-collections).

**Comment by vreuter** [comment]
Thanks @Tinche
