### ISSUE TITLE
Add support for pathlib.Path

### ISSUE THREAD

**Issue by spacemanspiff2007** [python-attrs/cattrs#81]
* cattrs version: 0.9.0
* Python version: 3.7
* Operating System: Win

### Description
I am trying to serialize a class with a pathlib.Path object

### What I Did

```python
from pathlib import Path
import attr

@attr.s
class PathTest():
    my_path: Path = attr.ib(default=Path('c:/test'))

cattr.structure({'my_path': 'c:/my_filepath',}, PathTest)
```
Error:
````
ValueError: Unsupported type: <class 'pathlib.Path'>. Register a structure hook for it.
````

The fix is easy, but I really feel like this is a fundamental type and should be supported out of the box
```python
cattr.register_structure_hook(Path, lambda d, t: Path(d))
cattr.register_unstructure_hook(Path, lambda d: str(d))
```

**Comment by henryiii** [comment]
This would be very nice, I'd be willing to take a stab at implementing if this is deemed a good idea. I think it could be `cattr.register_unstructure_hook(Path, os.fspath)`.

**Comment by Tinche** [comment]
I'm not sure this is useful enough to be included by default, but a recipe in the Usages section of the docs would be cool!

**Comment by rklasen** [comment]
@Tinche , I just stumbled over this too. I think support for Pathlib would be very useful, because the way I understand it, pathlib is supposed to be a modern replacement for os.path.

**Comment by Tinche** [comment]
Two things:

* I don't want cattrs to be a kitchen-sink type of library, since it increases complexity and maintenance burden
* I do want cattrs to be a kind of meta-framework, i.e. a tool that you use as a base to create your own mini-framework for de/serialization

More fundamentally, this approach is also how I think good software should be architected.

As the OP rightly points out, adding support for `pathlib.Path` is literally two lines of code. So the way we handle this is we add a small section to the Usage Examples page so our users can include this support in their converters if they want it, and learn a little cattrs in the process. I'd merge this PR in a heartbeat.

**Comment by spacemanspiff2007** [comment]
I absolutely agree with you:
Support for every datatype will unnecessarily inflate cattrs.

However `pathlib.Path` is the recommended way to deal with file paths and it's part of the python standard installation which makes it a bit different. It is like `Enum`, which you support out of the box, too and is also not a built-in datatype.

**Comment by Tinche** [comment]
Alright, I consuled some other folks and I've changed my mind. Let's add this.

**Comment by rklasen** [comment]
Thank you, I really appreciate this!

**Comment by brendan-simon-indt** [comment]
Awesome.  I use `Path` everywhere ;-)

**Comment by aarnphm** [comment]
This is just a lack of lambda supports for type inference right?
a workaround would look something like:
```python
_convert_str: t.Callable[[t.Any], str] = lambda d: str(d)

cattr.register_unstructure_hook(Path, _convert_str)
```

**Comment by brendan-simon-indt** [comment]
Yep, that works.  I love the way Python is supposed to be pseudocode like and easy to read and understand 😉 🙄 

My lazy workaround was:

```python
cattr.register_unstructure_hook( Path, lambda d: str(d) )       # type: ignore
```

🤣

**Comment by Tinche** [comment]
Fixed on `main`!
